github: ITomPoland
# Możesz odkomentować poniższe opcje, jeśli założysz tam konta:
# ko_fi: ITomPoland
# buy_me_a_coffee: ITomPoland
# patreon: ITomPoland

custom: 
  - https://github.com/sponsors/ITomPoland
  # - https://www.awwwards.com/ITomPoland # Super opcja na przyszłość, żeby pokazać swój profil Awwwards!
